image: node:latest

before_script:
 - npm prune
 - npm install
 - npm install -g firebase-tools

stages:
 - build
 - deploy

cache:
  paths:
   - node_modules/
  key: “$CI_BUILD_REPO”

project_build:
 stage: build
 script: 
 - echo "----------------- Starting Deploy -----------------"
#  - git rev-parse --is-inside-work-tree
 - cd "$CI_PROJECT_DIR"/public/gi && ls 
 - cp "$CI_PROJECT_DIR"/src/index.html "$CI_PROJECT_DIR"/public/index.html
 - ls
 - echo "----------------- Starting Deploy -----------------"

firebase_deploy:
 stage: deploy
 script:
  - firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY
 environment:
  name: production
  url: https://afrostore-141ed.web.app/
 only:
  - master