image: node:latest

before_script:
 - npm prune
 - npm install
 - npm install -g firebase-tools

stages:
 - build
 - deploy

cache:
  paths:
   - node_modules/
  key: “$CI_BUILD_REPO”

git_check:
 stage: build
 script: 
  - echo "hello world"

# firebase_deploy:
#  stage: deploy
#  script:
#   - firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY
#  environment:
#   name: production
#   url: https://afrostore-141ed.web.app/
#  only:
#   - master