language: node_js
node_js: node

before_script:
 - ./scripts/build.sh
 - npm install -g firebase-tools

script:
 - echo "_____________________________ Begining Deploy  _____________________________"
 - firebase deploy --token $FIREBASE_TOKEN --non-interactive
 - echo "_____________________________ Deploy Finish _____________________________"